language: 
  - python
  
python:
  - "3.6"
  
services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install psycopg2-binary
  
before_script:
  - export FLASK_APP='run.py'
  - psql -c 'create database test_orders;' -U postgres
  - export DB_URL='postgresql://postgres@localhost:5432/test_orders'
  - flask create

script:
  - pytest --cov=app

after_success:
  - coveralls
